#!/usr/bin/env bash
# Build the parts of ggml's Hexagon (NPU) backend that only Qualcomm's own
# toolchain can produce, and stage them into native/hexagon/.
#
#   ./tools/build-hexagon.sh
#
# Why this exists as a separate step rather than a flag in CMakeLists.txt:
#
# The NPU is a second processor with its own instruction set, so the backend
# comes in two halves. The host half is ordinary arm64 Android code and the
# app's normal NDK build compiles it. The device half — libggml-htp-v<NN>.so,
# which runs *on* the DSP — needs hexagon-clang, and the fastRPC glue between
# them is generated by `qaic` from an IDL file. Both live only in the Hexagon
# SDK, and the SDK is not a public download: Qualcomm serves it through
# Qualcomm Package Manager behind a developer account and a licence click, so
# there is no URL for a build script to fetch.
#
# llama.cpp publishes a toolchain image with the SDK already installed in it,
# and ghcr.io needs no account. So the account-gated toolchain is used exactly
# once, here, to produce four small binaries and two generated C files; after
# that the app builds on any machine with the NDK and no Qualcomm anything.
#
# Nothing produced here is checked in (native/hexagon/ is ignored) — it is
# derived from the pinned llama.cpp checkout, and re-derivable by re-running
# this.

set -euo pipefail

image="ghcr.io/snapdragon-toolchain/arm64-android:v0.7"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

if [[ ! -d native/llama.cpp ]]; then
    echo "!! native/llama.cpp is missing — run ./tools/fetch-native.sh first." >&2
    exit 1
fi

out="native/hexagon"
mkdir -p "$out"

# Docker on Windows wants a Windows path on the left of a --volume, and this
# script is run from Git Bash, which hands out /c/... ones. cygpath is the
# translation and exists only where the problem does.
hostpath() {
    if command -v cygpath > /dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi
}

# MSYS would otherwise rewrite the container-side half of each --volume, and
# the paths inside the -c script, into Windows paths as well.
export MSYS2_ARG_CONV_EXCL="*"

# --platform because the image is x86_64: an arm64 host has to be told to
# emulate rather than left to refuse.
docker run --rm --platform linux/amd64 \
    --volume "$(hostpath "$(pwd)/native/llama.cpp"):/src:ro" \
    --volume "$(hostpath "$(pwd)/$out"):/out" \
    "$image" /bin/bash -euo pipefail -c '
      # A read-only source mount and a build tree beside it: the app builds the
      # same checkout with a different toolchain, and neither should see the
      # other s CMake cache.
      cmake -S /src -B /tmp/build -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-31 \
        -DCMAKE_BUILD_TYPE=Release \
        -DHEXAGON_SDK_ROOT="$HEXAGON_SDK_ROOT" \
        -DPREBUILT_LIB_DIR=android_aarch64 \
        -DGGML_HEXAGON=ON \
        -DGGML_OPENCL=OFF \
        -DGGML_OPENMP=OFF \
        -DGGML_LLAMAFILE=OFF \
        -DLLAMA_BUILD_COMMON=OFF \
        -DLLAMA_BUILD_TESTS=OFF \
        -DLLAMA_BUILD_TOOLS=OFF \
        -DLLAMA_BUILD_EXAMPLES=OFF \
        -DLLAMA_BUILD_SERVER=OFF \
        -DLLAMA_BUILD_APP=OFF \
        -DLLAMA_BUILD_UI=OFF \
        -DLLAMA_CURL=OFF \
        -DLLAMA_OPENSSL=OFF

      # The DSP images and, as a side effect of configuring the host half, the
      # generated fastRPC stub. Nothing else from this build is used.
      cmake --build /tmp/build --target ggml-hexagon htp-v73 htp-v75 htp-v79 htp-v81

      hex=/tmp/build/ggml/src/ggml-hexagon
      mkdir -p /out/skel /out/generated /out/incs

      cp "$hex"/libggml-htp-v*.so /out/skel/
      cp "$hex"/htp_iface_stub.c "$hex"/htp_iface.h /out/generated/

      # The SDK headers the host half includes (AEEStdErr.h, rpcmem.h,
      # remote.h, dspqueue.h, and domain.h from the examples). Copied rather
      # than referenced so the app build needs no SDK at all.
      cp -r "$HEXAGON_SDK_ROOT"/incs/. /out/incs/
      cp "$HEXAGON_SDK_ROOT"/utils/examples/domain.h /out/incs/ 2>/dev/null || true

      chmod -R a+rwX /out
    '

echo
echo "Staged into $out:"
ls -la "$out/skel"
